feat: handle shutdown gracefully, draining in-flight requests
When server is shut down (e.g. when rotating instances or scaling down number of
instances), shut down signal should allow in-process requests to be completed
rather than immediately shutting down. And it doesn't need to be logged as a
fatal error: it's fatal to the server, but not an error!